### PR TITLE
Fix jms_serializer.json_serialization_visitor default options

### LINKED ISSUE #755: Since 3.4.0, JSON_PRESERVE_ZERO_FRACTION is no longer the default value `json_encode`
It looks like #749  caused a regression.

Before #749, the default value of `jms_serializer.visitors.json_serilization:options` which is 0 was ignored because an `!empty` check was used. So the `setOptions` method call was not added to the container builder (https://github.com/schmittjoh/JMSSerializerBundle/blob/2842e767bd0e64310ab803e05bb5f676c81c0bbe/DependencyInjection/JMSSerializerExtension.php#L198-L201).

In this case the `JMS\Serializer\JsonSerializationVisitor::$options` default (`JSON_PRESERVE_ZERO_FRACTION`) was used.

Now, the `!empty` check was replaced by a `!isset` check. By doing so, the default value of 0 is now used.

I suggest to set the default value of `jms_serializer.visitors.json_serilization:options` to `JSON_PRESERVE_ZERO_FRACTION` to fix the regression and keep the benefits of #749.

### PR DESCRIPTION
**Pull request by fbourigault**
Fix #755.

### CODE REVIEW

File: DependencyInjection/Configuration.php [hunk 1]
```diff
@@ -279,7 +279,7 @@ private function addVisitorsSection(NodeBuilder $builder)
                         ->children()
                             ->scalarNode("depth")->end()
                             ->scalarNode('options')
-                                ->defaultValue(0)
+                                ->defaultValue(1024 /*JSON_PRESERVE_ZERO_FRACTION*/)
```
Comment (fbourigault) [inline DependencyInjection/Configuration.php]: I used the constant value to not introduce a hard dependency on `ext-json`.

**Comment by goetas** [comment]
Very good. Thanks
